### ISSUE TITLE
Controllable Order of Json Properties

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/abstract-data#2]
**Is your feature request related to a problem? Please describe.**
There is no way to configure the order that objects return their attributes in JSON Response. This leads to unintuitive responses though they are functionally the same. The order depends on the attribute names and their alphanumerical value and length it seems.

**Describe the solution you'd like**
I would like the order to be the same order in which the attributes are defined.

**Describe alternatives you've considered**
Otherwise adding annotations could achieve more fine-grained control, but seems too much and to verbose of a solution.

**Additional context**
To see the effect you can try:

```
public class Nonsense {
    public int a;
    public String b;

    public Nonsense(int test, String test2) {
        this.a = test;
        this.b = test2;
    }
}
```

and then 

```
public class Nonsense {
    public int c;
    public String b;

    public Nonsense(int test, String test2) {
        this.c = test;
        this.b = test2;
    }
}
```

with a controller like this:

```
public class RootController extends HttpController {

    @Inject
    public WebApplication webApplication;

    @Get("/")
    public Nonsense getRoot() {
        return new Nonsense(23, "HET");
    }

}
```

**Comment by JanHolger** [comment]
Unfortunately sorting by line number isn't that trivial as the Reflection API does not offer line numbers. You are probably refering to [this](https://stackoverflow.com/questions/1097807/java-reflection-is-the-order-of-class-fields-and-methods-standardized#comment108421787_1098251) answer on a stackoverflow question regarding this problem but this is reading and analyzing the bytecode from the .class file. This solution is pretty horrible performance and stability wise. It depends on the way the classloader accesses the classfiles which depends on the runtime environment. At the moment we are internally using gson for class mapping aswell as json parsing/dumping. We have plans to replace the class mapping part with our own solution but we intended to still use gson as json parser/dumper and i'm not sure if the json dumper respects order as per JSON specification properties should have no specific order. We should keep this issue open and look into it, when we build our own class mapping.

**Comment by x7airworker** [comment]
I think this one is fixed, through the new `order` property of the `MapperOptions` annotation.
